env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - off
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  func-call-spacing:
    - error
    - always
    - { "allowNewlines": true }
  no-unexpected-multiline:
    - off
overrides:
  files: [".mjs"]
