env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - off
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  func-call-spacing:
    - error
    - always
    - { "allowNewlines": true }
  no-unexpected-multiline:
    - off
  array-bracket-spacing:
    - error
    - always
  arrow-body-style:
    - error
    - never
  prefer-arrow-callback:
    - error
    - { allowNamedFunctions: false, allowUnboundThis: false }
  no-var:
    - error
  prefer-const:
    - error
  prefer-template:
    - error
  comma-dangle:
    - error
    - never
  no-ternary:
    - error
overrides:
  files: [".mjs"]
