language: node_js
node_js:
  - "10.3.0"
install:
  - npm install
script:
  - npm run build
  - npm run test

deploy:
  on:
    branch: master
  script:
    - ssh-add - <<< "${SSH_PRIVATE_KEY}"
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git version patch -m "Version %s [skip ci]"
    - git push --tags
