language: node_js
node_js:
  - "10.3.0"

addons:
  ssh_known_hosts:
    - github.com

stages:
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      node_js:
        - "10.3.0"
      script:
        - npm run build
    - stage: test
      node_js:
        - "10.3.0"
      script:
        - npm run test

deploy:
  provider: script
  script: ./travis/deploy.sh
  on:
    branch: master
