language: node_js
node_js:
  - "10.3.0"

cache:
  directories:
    - node_modules

addons:
  ssh_known_hosts:
    - github.com

stages:
#  - build
#  - test
  - deploy
##    if: branch = master

jobs:
  include:
    # - stage: build
    #   node_js:
    #     - "10.3.0"
    #   script:
    #     - npm ci
    #     - npm run build
    # - stage: test
    #   node_js:
    #     - "10.3.0"
    #   script:
    #     - npm run test
    - stage: deploy
      node_js:
        - "10.3.0"
      script:
        - mkdir -p ~/.shh
        - echo $SSH_PRIVATE_KEY > ~/.ssh/mojiscript_rsa
        - eval `ssh-agent -s`
        - chmod 600 ~/.ssh/mojiscript_rsa
        - ssh-add ~/.ssh/mojiscript_rsa

        - npm version patch -m "Version %s [skip ci]"
        - git push --tags git@github.com:joelnet/MojiScript.git develop

# deploy:
#   on:
#     branch: master
#   script:
#     - ssh-add - <<< "${SSH_PRIVATE_KEY}"
#     - ssh-keyscan github.com >> ~/.ssh/known_hosts
#     - git version patch -m "Version %s [skip ci]"
#     - git push --tags
