language: node_js
node_js:
  - "10.3.0"

cache:
  directories:
    - node_modules

stages:
  - build
  - test
  - deploy
##    if: branch = master

jobs:
  include:
    - stage: build
      node_js:
        - "10.3.0"
      script:
        - npm ci
        - npm run build
    - stage: test
      node_js:
        - "10.3.0"
      script:
        - npm run test
    - stage: deploy
      node_js:
        - "10.3.0"
      script:
        - eval `ssh-agent -s`
        - ssh-add - <<< "${SSH_PRIVATE_KEY}"
        - ssh-keyscan github.com >> ~/.ssh/known_hosts
        - git version patch -m "Version %s [skip ci]"
        - git push --tags

# deploy:
#   on:
#     branch: master
#   script:
#     - ssh-add - <<< "${SSH_PRIVATE_KEY}"
#     - ssh-keyscan github.com >> ~/.ssh/known_hosts
#     - git version patch -m "Version %s [skip ci]"
#     - git push --tags
